"""Version of the divtel package.

``divtel/_version.py`` is generated by setuptools_scm at build time and is not
tracked in git. When it is missing -- e.g. when running from a source tree that
was never built -- fall back to the metadata of the installed distribution.
"""

try:
    from ._version import __version__
except ImportError:
    from importlib.metadata import PackageNotFoundError, version

    try:
        __version__ = version("divtel")
    except PackageNotFoundError:
        __version__ = "0.0.0"

__all__ = ["__version__"]
